### ISSUE TITLE
Nexus Login required

### ISSUE THREAD

**Issue by ghost** [K15t/spark#25]
Hello,

when I run atlas-debug I get this error message:
`[ERROR] Failed to execute goal on project spa: Could not resolve dependencies for project xxx.xxx.xxx:atlassian-plugin:1.0.0-SNAPSHOT: Failed to collect dependencies at com.k15t.spark:spark-confluence:jar:2.2.0: Failed to read artifact descriptor for com.k15t.spark:spark-confluence:jar:2.2.0: Could not transfer artifact com.k15t.scroll.dependencies:confluence-dep-5-10:pom:3 from/to spark-repo (https://nexus.k15t.com/content/repositories/releases): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]`

Regards,
Jan

**Comment by jensrutschmann** [comment]
Hi @janszczepanski ,

I've updated the permissions on our nexus server, please retry the download.
You might need to 'convince' Maven by removing any timestamp or lock files for the affected paths from your local maven repo first though.

Cheers,
Jens

**Comment by adi928** [comment]
This is happening again.
```
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project scroll-webhelp-theme: Could not resolve dependencies for project com.k15t.scroll:scroll-webhelp-theme:atlassian-plugin:1.1.32-SNAPSHOT: Failed to collect dependencies at com.k15t:k15t-third-party-license-def:license.properties:4: Failed to read artifact descriptor for com.k15t:k15t-third-party-license-def:license.properties:4: Could not transfer artifact com.k15t:k15t-third-party-license-def:pom:4 from/to k15t (https://nexus.k15t.com/content/repositories/releases/): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]
[ERROR]
```

**Comment by jensrutschmann** [comment]
@adi928 Sorry for that. Looks like that license definition dependency got added when we updated the master pom version.

I've just added this dependency to the public artifacts, so you should be able to download it now. Also see my previous answer.

----

For the record: this is not a spark problem but related to https://bitbucket.org/K15t/scroll-webhelp-theme instead
