### ISSUE TITLE
Unable to build on apple silicon

### ISSUE THREAD

**Issue by yours-truly-phil** [K15t/spark#40]
This won't build on apple silicon due to an old version of the frontend-maven-plugin.

This should be fixed with upping the version to 1.11.3

```
<groupId>com.github.eirslett</groupId>
<artifactId>frontend-maven-plugin</artifactId>
<version>1.11.3</version>
```

**Comment by jensrutschmann** [comment]
@yours-truly-phil See this WIP branch: https://github.com/K15t/spark/tree/DEV-114-frontend-build-updates
